/**
 * GENERATED FILE — do not hand-edit. Produced by scripts/extract-sprites.ts from the reference
 * sprite sheet ("The Tower - Sprite Sheet (7).html", section 10 "THE SHEET"). Regenerate with:
 *   npx tsx scripts/extract-sprites.ts "<path to reference sheet.html>"
 */

export interface SpriteGrid {
  readonly w: number;
  readonly h: number;
  readonly rows: readonly string[];
  readonly hb: boolean;
  readonly map?: Readonly<Record<string, string | readonly string[]>>;
}

export type SheetZone = "stone" | "cistern" | "ruin" | "forge" | "crypt" | "throne";

export type ArmourTierId = "none" | "leather" | "mail" | "plate";

export interface ArmourTierDef {
  readonly label: string;
  readonly regions: string;
  readonly mid?: string;
  readonly dark?: string;
  readonly accent?: string;
}

export const PAL: Readonly<Record<string, string>> = {
  "K": "#0a0b10",
  "D": "#1b2133",
  "S": "#2f3a5c",
  "M": "#4a5c8a",
  "L": "#7e91bd",
  "W": "#d3dff5",
  "b": "#2a1a12",
  "B": "#57381f",
  "R": "#8b5a30",
  "T": "#c99a54",
  "G": "#8a6a1e",
  "Y": "#d9aa3b",
  "y": "#f7de8e",
  "r": "#6e1a1a",
  "e": "#c23a2c",
  "o": "#f07a3c",
  "f": "#ffd25e",
  "g": "#1f4a2b",
  "h": "#3c8a3b",
  "i": "#7cc45c",
  "p": "#34254c",
  "u": "#6b45a8",
  "v": "#ab86ea",
  "c": "#46d6e2",
  "n": "#eaf0fa",
  "m": "#9aa6bd",
  "I": "#333c4d",
  "N": "#6f7b90",
  "E": "#bcc6d6",
  "s": "#f2c49f",
  "w": "#c98f6d",
  "z": "#3f4a34",
  "q": "#6e8055",
  "Q": "#96a874",
  "X": "#2a1e15",
  "a": "#123a4a",
  "j": "#1c4a4a",
  "J": "#2f7a6a",
  "O": "#e6dcc0",
  "Z": "#b3a888",
  "t": "#c9b68a",
  "x": "#241f1c",
  "k": "#2b4a25",
  "l": "#5f9b3f",
  "hb:out": "#1c0e1e",
  "hb:skin": "#d98f6a",
  "hb:wine": "#6a2238",
  "hb:steel": "#7f8cad",
  "hb:gold": "#b8802a",
  "hb:leather": "#6a4228",
  "hb:goblin": "#3a5e2a",
  "hb:bone": "#d0bc92",
  "hb:rust": "#9a4a22",
  "hb:ember": "#ff7a3a",
  "hb:arcane": "#7658a0",
  "hb:cyan": "#46d6e2",
  "hb:ooze": "#459c7c",
  "hb:hide": "#565b34"
};

export const C: Readonly<Record<string, string>> = {
  "K": "#1a1020",
  "k": "#2e1f33",
  "q": "#6b3a34",
  "w": "#a8604a",
  "s": "#d98f6a",
  "S": "#f0c09a",
  "h": "#2a1818",
  "H": "#5a3024",
  "j": "#8a4a2c",
  "n": "#2a2f45",
  "N": "#4a5474",
  "m": "#7f8cad",
  "M": "#c3cfe6",
  "X": "#ffffff",
  "y": "#6a4418",
  "Y": "#b8802a",
  "Z": "#f0c850",
  "r": "#3a1426",
  "R": "#6a2238",
  "P": "#9a3448",
  "l": "#3a2418",
  "L": "#6a4228",
  "T": "#9a6a3a",
  "g": "#1e3420",
  "G": "#3a5e2a",
  "v": "#6a8e34",
  "V": "#a8c050",
  "e": "#a02020",
  "E": "#ff7a3a",
  "b": "#5e4a3a",
  "B": "#9a8466",
  "c": "#d0bc92",
  "Q": "#f2e6c4",
  "u": "#5a2a18",
  "U": "#9a4a22",
  "a": "#34361f",
  "A": "#565b34",
  "@": "#80874c",
  "p": "#24182f",
  "f": "#46305f",
  "F": "#7658a0",
  "O": "#46d6e2",
  "D": "#c4f7fa",
  "d": "#16322e",
  "W": "#28604f",
  "J": "#459c7c",
  "%": "#9ad8b8"
};

export const ARMOUR_TIERS: Readonly<Record<ArmourTierId, ArmourTierDef>> = {
  "none": {
    "label": "Unarmoured",
    "regions": ""
  },
  "leather": {
    "label": "Leather",
    "regions": "CV",
    "mid": "R",
    "dark": "B",
    "accent": "T"
  },
  "mail": {
    "label": "Mail",
    "regions": "CVPA",
    "mid": "N",
    "dark": "I",
    "accent": "N"
  },
  "plate": {
    "label": "Full plate",
    "regions": "CVPAH",
    "mid": "E",
    "dark": "N",
    "accent": "Y"
  }
};

export const ZONE_SWAPS: Readonly<Record<SheetZone, Readonly<Record<string, string>>>> = {
  "stone": {},
  "cistern": {
    "M": "j",
    "L": "J",
    "S": "D",
    "W": "c"
  },
  "ruin": {
    "M": "k",
    "L": "l",
    "S": "g",
    "D": "X"
  },
  "forge": {
    "M": "r",
    "L": "e",
    "S": "x",
    "D": "K",
    "W": "f"
  },
  "crypt": {
    "M": "Z",
    "L": "O",
    "S": "I",
    "D": "K"
  },
  "throne": {
    "M": "G",
    "L": "Y",
    "S": "b",
    "D": "X"
  }
};

/** Not a sheet sprite (research R9) — promotes lava's own ramp one step for its glow frame. */
export const LAVA_GLOW_SWAP: Readonly<Record<string, string>> = { x: "o", o: "f" };

export const SPRITES: Readonly<Record<string, SpriteGrid>> = {
  "player": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "................................",
      "...........KKKKKKKKKK...........",
      "..........KTTTTTTTTTTK..........",
      ".........KTTTTTTTTTTTTK.........",
      ".........KTRRRRRRRRRRTK.........",
      ".........KTTssssssssTTK.........",
      ".........KsssKssssKsssK.........",
      ".........KssssssssssssK.........",
      ".........KswsssssssswsK.........",
      ".........KsssswwwwssssK.........",
      "..........KssssssssssK..........",
      "..........KwwwwwwwwwwK..........",
      "........KSSSSSSSSSSSSSSK........",
      "........KSMMMMMMMMMMMMSK........",
      "........KsMMMMMMMMMMMMsK........",
      "........KsMMMMMMMMMMMMsK........",
      "........KsMMMMMMMMMMMMsK........",
      "........KsBBBBBBBBBBBBsK........",
      "........KsBBBBBYYBBBBBsK........",
      "........KsMMMMMMMMMMMMsK........",
      ".........KMMMMMMMMMMMMK.........",
      ".........KSSSSSSSSSSSSK.........",
      "..........KBBBBBKBBBBBK.........",
      "..........KBBBBBKBBBBBK.........",
      "..........KBBBBBKBBBBBK.........",
      "..........KBBBBBKBBBBBK.........",
      "..........KbbbbbKbbbbbK.........",
      "..........KbbbbbKbbbbbK.........",
      "..........DDDDDDDDDDDD..........",
      "................................"
    ],
    "hb": false
  },
  "goblin": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "...........KKKKKKKKKK...........",
      "..........KiiiiiiiiiiK..........",
      ".........KiiiiiiiiiiiiK.........",
      ".........KiiiiiiiiiiiiK.........",
      "......KhhKiiiiiiiiiiiiKhhK......",
      "......KhhKiiiiiiiiiiiiKhhK......",
      ".......KhKiiiiiiiiiiiiKhK.......",
      ".........KiieeiiiieeiiK.........",
      ".........KiiiiiiiiiiiiK.........",
      ".........KiiiWWWWWWiiiK.........",
      ".........KiihhhhhhhhiiK.........",
      "..........KhhhhhhhhhhK..........",
      "..........KggggggggggK..........",
      ".........KBBBBBBBBBBBBK.........",
      ".........KiBBBBBBBBBBiK.........",
      ".........KiBBBBBBBBBBiK.........",
      ".........KiiiiiiiiiiiiK.........",
      ".........KiiiiiiiiiiiiK.........",
      ".........KhhhhhhhhhhhhK.........",
      "..........KBBBBBBBBBBK..........",
      "..........KbbbbbbbbbbK..........",
      "..........KhhhhKKhhhhK..........",
      "..........KhhhhKKhhhhK..........",
      "..........KggggKKggggK..........",
      "..........KbbbbKKbbbbK..........",
      "..........DDDDDDDDDDDD..........",
      "................................"
    ],
    "hb": false
  },
  "ogre": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "................................",
      "............KKKKKKKK............",
      "...........KQQQQQQQQK...........",
      "..........KQQQQQQQQQQK..........",
      "..........KQKWQQQQKWQK..........",
      "..........KQQQQQQQQQQK..........",
      "..........KQWqqqqqqWQK..........",
      "...........KqqqqqqqqK...........",
      "............DDDDDDDD............",
      ".........KqqqqqqqqqqqqK.........",
      ".....KqqqqqqqqqqqqqqqqqqqqK.....",
      "....KqqqqqqqqqqqqqqqqqqqqqqK....",
      "....KqQQQQQQQQQQQQQQQQQQQQqK....",
      "....KQQQQQQQQQQQQQQQQQQQQQQK....",
      "....KQQQQQQQQQQQQQQQQQQQQQQK....",
      "....KQBBBBBBBBQQQQBBBBBBBBQK....",
      "....KQQQQQQQQQQQQQQQQQQQQQQK....",
      "....KQQQQQQQQQQQQQQQQQQQQQQK....",
      "....KBBBBBBBBBBBBBBBBBBBBBBK....",
      "....KBBBBBBBBBYYYYBBBBBBBBBK....",
      ".....KqqqqqqqqqqqqqqqqqqqqK.....",
      "......KqqqqqqqqqqqqqqqqqqK......",
      ".......KqqqqqqKKKKqqqqqqK.......",
      ".......KqqqqqqKKKKqqqqqqK.......",
      ".......KqqqqqqKKKKqqqqqqK.......",
      ".......KzzzzzzKKKKzzzzzzK.......",
      ".......KzzzzzzKKKKzzzzzzK.......",
      "......KbbbbbbbKKKKbbbbbbbK......",
      "......DDDDDDDDDDDDDDDDDDDD......",
      "................................"
    ],
    "hb": false
  },
  "wizard": {
    "w": 32,
    "h": 32,
    "rows": [
      "...............KK...............",
      "..............KuuK..............",
      "..............KuuK..............",
      ".............KuuuuK.............",
      ".............KuuuuK.............",
      "............KuuuuuuK............",
      "............KuuuuuuK............",
      "...........KuuuuuuuuK...........",
      "...........KuuuyyuuuK...........",
      "..........KuuuuuuuuuuK..........",
      "..........KuuuuuuuuuuK..........",
      ".........KppppppppppppK.........",
      ".........KDDDDDDDDDDDDK.........",
      ".........KDDcccDDcccDDK.........",
      ".........KDDDDDDDDDDDDK.........",
      ".........KDDDDDDDDDDDDK.........",
      "..........KnnnnnnnnnnK..........",
      "..........KnnnnnnnnnnK..........",
      ".........KuuuuuuuuuuuuK.........",
      ".........KuuuuuuuuuuuuK.........",
      "........KmuuuuuuuuuuuumK........",
      "........KmuuuuuuuuuuuumK........",
      "........KmuuuvvvvvvuuumK........",
      ".........KuuuuvvvvuuuuK.........",
      ".........KuuuuuuuuuuuuK.........",
      "........KuuuuuuuuuuuuuuK........",
      "........KuuuuuuuuuuuuuuK........",
      ".......KppppppppppppppppK.......",
      "......KppppppppppppppppppK......",
      "......KppppppppppppppppppK......",
      "......DDDDDDDDDDDDDDDDDDDD......",
      "................................"
    ],
    "hb": false
  },
  "playerArmour": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "................................",
      "................................",
      "..........hHHHHHHHHHHh..........",
      ".........hHHHHHHHHHHHHh.........",
      ".........hHHHHHHHHHHHHh.........",
      ".........hHH........HHh.........",
      ".........hHH........HHh.........",
      "..........hHH......HHh..........",
      "................................",
      "................................",
      "................................",
      "................................",
      "........pCCCCCCCCCCCCCCp........",
      "........pPPCCCCCCCCCCPPp........",
      "........pPPCCCCCCCCCCPPp........",
      ".........cCCCCCCCCCCCCc.........",
      ".........cCCCCCCCCCCCCc.........",
      "........aACCCCCCCCCCCCAa........",
      "........aACCCCCCCCCCCCAa........",
      ".........cCCCCCCCCCCCCc.........",
      ".........cCCCCCCCCCCCCc.........",
      "................................",
      "................................",
      "................................",
      "................................",
      "..........vVVVVVvVVVVVv.........",
      "..........vVVVVVvVVVVVv.........",
      "..........vVVVVVvVVVVVv.........",
      "................................",
      "................................"
    ],
    "hb": false
  },
  "floorSlab": {
    "w": 16,
    "h": 16,
    "rows": [
      "KKKKKKKKKKKKKKKK",
      "SSSSSSSSSSSSSSSS",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDSDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "KKKKKKKKKKKKKKKK",
      "SSSSSSSSSSSSSSSS",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDSDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD"
    ],
    "hb": false
  },
  "floorCracked": {
    "w": 16,
    "h": 16,
    "rows": [
      "KKKKKKKKKKKKKKKK",
      "SSSSSSSSSSSSSSSS",
      "DDDDDDDDDDDDDDDD",
      "DDDDKDDDDDDDDDDD",
      "DDDDDKDDDDDDDDDD",
      "DDDDDDKDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "KKKKKKKKKKKKKKKK",
      "SSSSSSSSSSSSSSSS",
      "DDDDDDDDDDDDDDDD",
      "DDKDDDDDDDDDDDDD",
      "DDDKDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD"
    ],
    "hb": false
  },
  "wallBlock": {
    "w": 16,
    "h": 16,
    "rows": [
      "LLLLLLLLLLLLLLLL",
      "MMMMMMMMMMMMMMMM",
      "SMMMMMMKSMMMMMMK",
      "SMMMMMMKSMMMMMMK",
      "SMMMMMMKSMMMMMMK",
      "SSSSSSSKSSSSSSSK",
      "KKKKKKKKKKKKKKKK",
      "MMMMMMMMMMMMMMMM",
      "MMMMKMMMMMMKMMMM",
      "MMMMKMMMMMMKMMMM",
      "MMMMKMMMMMMKMMMM",
      "SSSSKSSSSSSKSSSS",
      "KKKKKKKKKKKKKKKK",
      "MMMMMMMMMMMMMMMM",
      "SMMMMMMKSMMMMMMK",
      "SMMMMMMKSMMMMMMK"
    ],
    "hb": false
  },
  "crackedWall": {
    "w": 16,
    "h": 16,
    "rows": [
      "LLLLLLLLLLLLLLLL",
      "MMMMMMMMMMMMMMMM",
      "SMMMMMMKSMMKMMMK",
      "SMMMMMMKSMKKMMMK",
      "SMMMMMMKSMKMMMMK",
      "SSSSSSSKSKKSSSSK",
      "KKKKKKKKKKKKKKKK",
      "MMMMMMMMMMMMMMMM",
      "MMMMKMMMMKMKMMMM",
      "MMMMKMMMKMMKMMMM",
      "MMMMKMMKKMMKMMMM",
      "SSSSKSKSSSSKSSSS",
      "KKKKKKKKKKKKKKKK",
      "MMMMMMMMMMMMMMMM",
      "SMMMMKMKSMMMMMMK",
      "SMMMKKMKSMMMMMMK"
    ],
    "hb": false
  },
  "water": {
    "w": 16,
    "h": 16,
    "rows": [
      "aaaaaaaaaaaaaaaa",
      "aaaaaaaaaaaaaaaa",
      "aajjjjjaaaaaaaaa",
      "aaaaaaaaaaaaaaaa",
      "aaaaaaaajjjjjjaa",
      "aaaaaaaaaaaaaaaa",
      "aaaaLLLaaaaaaaaa",
      "aaaaaaaaaaaaaaaa",
      "aaaaaaaaaaaaaaaa",
      "aaaaaaaaaajjjjja",
      "aaaaaaaaaaaaaaaa",
      "ajjjjaaaaaaaaaaa",
      "aaaaaaaaaaaaaaaa",
      "aaaaaaaaaaaaLLLa",
      "aaaaaaaaaaaaaaaa",
      "aaaaaaaaaaaaaaaa"
    ],
    "hb": false
  },
  "spikesOff": {
    "w": 16,
    "h": 16,
    "rows": [
      "KKKKKKKKKKKKKKKK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDKKKDDKKKDDKKKK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDKKKDDKKKDDKKKK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KKKKKKKKKKKKKKKK"
    ],
    "hb": false
  },
  "spikesHalf": {
    "w": 16,
    "h": 16,
    "rows": [
      "KKKKKKKKKKKKKKKK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "DDWDDDWDDDWDDDWD",
      "DEEEDEEEDEEEDEEE",
      "KIIIKIIIKIIIKIII",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "DDWDDDWDDDWDDDWD",
      "KIIIKIIIKIIIKIII",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KKKKKKKKKKKKKKKK"
    ],
    "hb": false
  },
  "spikesOn": {
    "w": 16,
    "h": 16,
    "rows": [
      "KKKKKKKKKKKKKKKK",
      "KDDDDDDDDDDDDDDK",
      "DDWDDDWDDDWDDDWD",
      "DEEEDEEEDEEEDEEE",
      "DEEEDEEEDEEEDEEE",
      "KIIIKIIIKIIIKIII",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "DDWDDDWDDDWDDDWD",
      "DEEEDEEEDEEEDEEE",
      "KIIIKIIIKIIIKIII",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KDDDDDDDDDDDDDDK",
      "KKKKKKKKKKKKKKKK"
    ],
    "hb": false
  },
  "lava": {
    "w": 16,
    "h": 16,
    "rows": [
      "oooooxxxoooooooo",
      "xxxxoooooxxxoooo",
      "xxoooooooxxooooo",
      "oooooooofffooooo",
      "oooooofffffooooo",
      "xxxooooofffooooo",
      "xxoooooooooxxooo",
      "oooooooffffooooo",
      "ooooffffoooxxooo",
      "ooxxxooooooxxooo",
      "ooooofffoooooooo",
      "oooooooooxxxoooo",
      "xxxooooooffffooo",
      "ooooooxxxooooooo",
      "xxoooooxxxoooooo",
      "ooooooooffffoooo"
    ],
    "hb": false
  },
  "woodSword": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "................",
      "............+=..",
      "...........+=...",
      "..........+=....",
      ".........+=.....",
      "........+=......",
      "...<...+=.......",
      "....>.+=........",
      ".....>=.........",
      "....~.>.........",
      "...~...<........",
      "..>.............",
      ".<..............",
      "................"
    ],
    "hb": true,
    "map": {
      "=": "#6a4228",
      "+": "#9a6a3a",
      "<": "#3a2418",
      ">": "#6a4228",
      "~": "#2a1a12"
    }
  },
  "sword": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "..............+.",
      ".............+=.",
      "............+=..",
      "...........*=...",
      "..........+=....",
      ".........+=.....",
      "........+=......",
      "...<...+=.......",
      "....>.+=........",
      ".....>=.........",
      "....~.>.........",
      "...~...<........",
      "..>.............",
      ".<..............",
      "................"
    ],
    "hb": true,
    "map": {
      "=": "m",
      "+": "M",
      "*": "X",
      "<": "N",
      ">": "m",
      "~": "l"
    }
  },
  "goldSword": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "..............+.",
      ".............+=.",
      "............+=..",
      "...........*=...",
      "..........+=....",
      ".........+=.....",
      "........+=......",
      "...<...+=.......",
      "....>.+=........",
      ".....>=.........",
      "....~.>.........",
      "...~...<........",
      "..>.............",
      ".<..............",
      "................"
    ],
    "hb": true,
    "map": {
      "=": "Y",
      "+": "Z",
      "*": "#fff4c0",
      "<": "y",
      ">": "Y",
      "~": "l"
    }
  },
  "diamondSword": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "..............+.",
      ".............+=.",
      "............+=..",
      "...........*=...",
      "..........+=....",
      ".........+=.....",
      "........+=......",
      "...<...+=.......",
      "....>.+=........",
      ".....>=.........",
      "....~.>.........",
      "...e...<........",
      "..>.............",
      ".<..............",
      "................"
    ],
    "hb": true,
    "map": {
      "=": "#3aa8c8",
      "+": "#a8eef8",
      "*": "X",
      "<": "y",
      ">": "Z",
      "~": "l"
    }
  },
  "leatherHelm": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "......FFFF......",
      ".....FAAAAF.....",
      "....FACCCCAF....",
      "...FACCAACCAF...",
      "...FAAAAAAAAF...",
      "...FUUUUUUUUF...",
      "...FAkkkkkkAF...",
      "...FAAAkkAAAF...",
      "...FAAAAAAAAF...",
      "...FFAAAAAAFF...",
      "....FFFFFFFF....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": "L",
      "C": "T",
      "F": "l",
      "U": "#2a1a12",
      "k": "K"
    }
  },
  "leatherChest": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "..FAAF....FAAF..",
      ".FACCAF..FACCAF.",
      ".FACCAAAAAACCAF.",
      ".FACAAAAAAAACAF.",
      "..FAACAAAACAAF..",
      "..FAACAAAACAAF..",
      "..FAAAAAAAAAAF..",
      "...FAAAUUAAAF...",
      "...FAAAUUAAAF...",
      "...FUUUUUUUUF...",
      "....FFFFFFFF....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": "L",
      "C": "T",
      "F": "l",
      "U": "#2a1a12",
      "k": "K"
    }
  },
  "leatherLegs": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "..FUUUUUUUUUUF..",
      "..FAACAAAACAAF..",
      "..FAACAAAACAAF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FUCUF..FUCUF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FAAAF..FAAAF..",
      "..FFFFF..FFFFF..",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": "L",
      "C": "T",
      "F": "l",
      "U": "#2a1a12",
      "k": "K"
    }
  },
  "leatherBoots": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "................",
      "..FAAF....FAAF..",
      "..FACF....FCAF..",
      "..FACF....FCAF..",
      "..FUUF....FUUF..",
      "..FACF....FCAF..",
      "..FACF....FCAF..",
      ".FAACF....FCAAF.",
      "FAAAAF....FAAAAF",
      "FFFFFF....FFFFFF",
      "................",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": "L",
      "C": "T",
      "F": "l",
      "U": "#2a1a12",
      "k": "K"
    }
  },
  "mailHelm": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "......FFFF......",
      ".....FAAAAF.....",
      "....FACCCCAF....",
      "...FACCAACCAF...",
      "...FAAAAAAAAF...",
      "...FUUUUUUUUF...",
      "...FAkkkkkkAF...",
      "...FAAAkkAAAF...",
      "...FAAAAAAAAF...",
      "...FFAAAAAAFF...",
      "....FFFFFFFF....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": [
        "#4a5474",
        "#7f8cad"
      ],
      "C": "M",
      "F": "n",
      "U": "N",
      "k": "K"
    }
  },
  "mailChest": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "..FAAF....FAAF..",
      ".FACCAF..FACCAF.",
      ".FACCAAAAAACCAF.",
      ".FACAAAAAAAACAF.",
      "..FAACAAAACAAF..",
      "..FAACAAAACAAF..",
      "..FAAAAAAAAAAF..",
      "...FAAAUUAAAF...",
      "...FAAAUUAAAF...",
      "...FUUUUUUUUF...",
      "....FFFFFFFF....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": [
        "#4a5474",
        "#7f8cad"
      ],
      "C": "M",
      "F": "n",
      "U": "N",
      "k": "K"
    }
  },
  "mailLegs": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "..FUUUUUUUUUUF..",
      "..FAACAAAACAAF..",
      "..FAACAAAACAAF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FUCUF..FUCUF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FAAAF..FAAAF..",
      "..FFFFF..FFFFF..",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": [
        "#4a5474",
        "#7f8cad"
      ],
      "C": "M",
      "F": "n",
      "U": "N",
      "k": "K"
    }
  },
  "mailBoots": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "................",
      "..FAAF....FAAF..",
      "..FACF....FCAF..",
      "..FACF....FCAF..",
      "..FUUF....FUUF..",
      "..FACF....FCAF..",
      "..FACF....FCAF..",
      ".FAACF....FCAAF.",
      "FAAAAF....FAAAAF",
      "FFFFFF....FFFFFF",
      "................",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": [
        "#4a5474",
        "#7f8cad"
      ],
      "C": "M",
      "F": "n",
      "U": "N",
      "k": "K"
    }
  },
  "plateHelm": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "......FFFF......",
      ".....FAAAAF.....",
      "....FACCCCAF....",
      "...FACCAACCAF...",
      "...FAAAAAAAAF...",
      "...FUUUUUUUUF...",
      "...FAkkkkkkAF...",
      "...FAAAkkAAAF...",
      "...FAAAAAAAAF...",
      "...FFAAAAAAFF...",
      "....FFFFFFFF....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": "m",
      "C": "M",
      "F": "n",
      "U": "Y",
      "k": "K"
    }
  },
  "plateChest": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "..FAAF....FAAF..",
      ".FACCAF..FACCAF.",
      ".FACCAAAAAACCAF.",
      ".FACAAAAAAAACAF.",
      "..FAACAAAACAAF..",
      "..FAACAAAACAAF..",
      "..FAAAAAAAAAAF..",
      "...FAAAUUAAAF...",
      "...FAAAUUAAAF...",
      "...FUUUUUUUUF...",
      "....FFFFFFFF....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": "m",
      "C": "M",
      "F": "n",
      "U": "Y",
      "k": "K"
    }
  },
  "plateLegs": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "..FUUUUUUUUUUF..",
      "..FAACAAAACAAF..",
      "..FAACAAAACAAF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FUCUF..FUCUF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FACAF..FACAF..",
      "..FAAAF..FAAAF..",
      "..FFFFF..FFFFF..",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": "m",
      "C": "M",
      "F": "n",
      "U": "Y",
      "k": "K"
    }
  },
  "plateBoots": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "................",
      "..FAAF....FAAF..",
      "..FACF....FCAF..",
      "..FACF....FCAF..",
      "..FUUF....FUUF..",
      "..FACF....FCAF..",
      "..FACF....FCAF..",
      ".FAACF....FCAAF.",
      "FAAAAF....FAAAAF",
      "FFFFFF....FFFFFF",
      "................",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "A": "m",
      "C": "M",
      "F": "n",
      "U": "Y",
      "k": "K"
    }
  },
  "keyBronze": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "......1221......",
      ".....1*3321.....",
      "....12....32....",
      "....12....32....",
      ".....123321.....",
      "......1221......",
      ".......23.......",
      ".......23.......",
      ".......23.......",
      ".......2322.....",
      ".......23.......",
      ".......2321.....",
      ".......23.......",
      ".......11.......",
      "................"
    ],
    "hb": true,
    "map": {
      "1": "#5a2e14",
      "2": "#9a5a2a",
      "3": "#d89a5a",
      "*": "X"
    }
  },
  "keySilver": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "......1221......",
      ".....1*3321.....",
      "....12....32....",
      "....12....32....",
      ".....123321.....",
      "......1221......",
      ".......23.......",
      ".......23.......",
      ".......23.......",
      ".......2322.....",
      ".......23.......",
      ".......2321.....",
      ".......23.......",
      ".......11.......",
      "................"
    ],
    "hb": true,
    "map": {
      "1": "#3a4258",
      "2": "#8a96b0",
      "3": "#dfe8f6",
      "*": "X"
    }
  },
  "keyGold": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "......1221......",
      ".....1*3321.....",
      "....12....32....",
      "....12....32....",
      ".....123321.....",
      "......1221......",
      ".......23.......",
      ".......23.......",
      ".......23.......",
      ".......2322.....",
      ".......23.......",
      ".......2321.....",
      ".......23.......",
      ".......11.......",
      "................"
    ],
    "hb": true,
    "map": {
      "1": "y",
      "2": "Y",
      "3": "Z",
      "*": "X"
    }
  },
  "potion": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "......lLLl......",
      "......lLLl......",
      "......5665......",
      ".......55.......",
      ".....556655.....",
      "....56777765....",
      "...56X8888765...",
      "...57X8888875...",
      "...5788888875...",
      "...5778888775...",
      "....57777775....",
      ".....555555.....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "5": "#2a3044",
      "6": "#9aa8c0",
      "7": "#5a0c1a",
      "8": "#a81e2e",
      "9": "#e85a5a"
    }
  },
  "potionAttack": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "......lLLl......",
      "......5665......",
      ".......55.......",
      "......5665......",
      "......5775......",
      ".....578875.....",
      ".....578875.....",
      "....57X88875....",
      "....57X88875....",
      "...5788888875...",
      "...5788888875...",
      "....57777775....",
      ".....555555.....",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "5": "#2a3044",
      "6": "#9aa8c0",
      "7": "p",
      "8": "#6a3aa8",
      "9": "F"
    }
  },
  "potionDefense": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "................",
      "......lLLl......",
      "......lLLl......",
      "......5665......",
      "....55566555....",
      "...5677777765...",
      "..57X888888875..",
      "..57X888888875..",
      "..577888888775..",
      "...5777777775...",
      "....55555555....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "5": "#2a3044",
      "6": "#9aa8c0",
      "7": "n",
      "8": "N",
      "9": "m"
    }
  },
  "coin": {
    "w": 16,
    "h": 16,
    "rows": [
      "................",
      "................",
      "................",
      ".....111111.....",
      "....12*33221....",
      "...12*3223321...",
      "...1232222321...",
      "...1232kk2321...",
      "...1232kk2321...",
      "...1232222321...",
      "...1222222221...",
      "....11222211....",
      ".....111111.....",
      "................",
      "................",
      "................"
    ],
    "hb": true,
    "map": {
      "1": "y",
      "2": "Y",
      "3": "Z",
      "k": "#4a2e0c",
      "*": "#fff4c0"
    }
  },
  "doorBronze": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "..........ssssssssssss..........",
      "........ssSSSSSSSSSSSSss........",
      ".......sSSttttttttttttSSs.......",
      "......sSts111111111111stSs......",
      ".....sSts12222222222221stSs.....",
      ".....sSs1223333333333221sSs.....",
      "....sSts1223222222223221stSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs12232223kk32223221sSs....",
      "....sSs12232223kk32223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "...ssSSssssssssssssssssssSSss...",
      "...ssssssssssssssssssssssssss...",
      "................................",
      "................................"
    ],
    "hb": true,
    "map": {
      "1": "#5a2e14",
      "2": "#9a5a2a",
      "3": "#d89a5a",
      "s": "#1b2133",
      "S": "#2f3a5c",
      "t": "#4a5c8a",
      "*": "#d89a5a",
      "k": "K"
    }
  },
  "doorSilver": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "..........ssssssssssss..........",
      "........ssSSSSSSSSSSSSss........",
      ".......sSSttttttttttttSSs.......",
      "......sSts111111111111stSs......",
      ".....sSts12222222222221stSs.....",
      ".....sSs1223333333333221sSs.....",
      "....sSts1223222222223221stSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs12232223kk32223221sSs....",
      "....sSs12232223kk32223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "...ssSSssssssssssssssssssSSss...",
      "...ssssssssssssssssssssssssss...",
      "................................",
      "................................"
    ],
    "hb": true,
    "map": {
      "1": "#3a4258",
      "2": "#8a96b0",
      "3": "#dfe8f6",
      "s": "#1b2133",
      "S": "#2f3a5c",
      "t": "#4a5c8a",
      "*": "#dfe8f6",
      "k": "K"
    }
  },
  "doorGold": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "..........ssssssssssss..........",
      "........ssSSSSSSSSSSSSss........",
      ".......sSSttttttttttttSSs.......",
      "......sSts111111111111stSs......",
      ".....sSts12222222222221stSs.....",
      ".....sSs1223333333333221sSs.....",
      "....sSts1223222222223221stSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs12232223kk32223221sSs....",
      "....sSs12232223kk32223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs1*23222222222232*1sSs....",
      "....sSs122322222222223221sSs....",
      "....sSs111111111111111111sSs....",
      "...ssSSssssssssssssssssssSSss...",
      "...ssssssssssssssssssssssssss...",
      "................................",
      "................................"
    ],
    "hb": true,
    "map": {
      "1": "y",
      "2": "Y",
      "3": "Z",
      "s": "#1b2133",
      "S": "#2f3a5c",
      "t": "#4a5c8a",
      "*": "Z",
      "k": "K"
    }
  },
  "stairsUp": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "................................",
      "...........kkkkkkkkkk...........",
      "..........kyYYYYYYYYyk..........",
      "..........kYZZZZZZZZYk..........",
      "..........kssssssssssk..........",
      ".........kSttttttttttSk.........",
      ".........kSSSSSSSSSSSSk.........",
      ".........kssssssssssssk.........",
      "........kSttttttttttttSk........",
      "........kSSSSSSSSSSSSSSk........",
      "........kSssssssssssssSk........",
      ".......kSttttttttttttttSk.......",
      ".......kSSSSSSSSSSSSSSSSk.......",
      ".......kSssssssssssssssSk.......",
      "......kSttttttttttttstttSk......",
      "......kSSSSSSSSSSSSSSsSSSk......",
      "......kSssssssssssssssssSk......",
      ".....kSttttttttttttttttttSk.....",
      ".....kSSSSSSSSSSSSSSSSSSSSk.....",
      ".....kSssssssssssssssssssSk.....",
      "....kSttttttttttttttttttttSk....",
      "....kSSSSsSSSSSSSSSSSSSSSSSk....",
      "....kSssssssssssssssssssssSk....",
      "...kSttttttttttttttttttttttSk...",
      "...kSSSSSSSSSSSSSSSSSSSSSSSSk...",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "................................",
      "................................",
      "................................",
      "................................"
    ],
    "hb": true,
    "map": {
      "s": "#1b2133",
      "S": "#2f3a5c",
      "t": "#7e91bd",
      "k": "#0e1018",
      "q": "#141824"
    }
  },
  "stairsDown": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "................................",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..kSttttttttttttttttttttttttSk..",
      "..kSSSSSSSSSSSSSSSSSSSSSSSSSSk..",
      "..kksssssssssssssssssssssssskk..",
      "...kkSSSSSSSSSSSSSSSSSSSSSSkk...",
      "...kksssssssssssssssssssssskk...",
      "....kkSSSSSSSSSSSSSSSSSSSSkk....",
      "....kksssssssssssssssssssskk....",
      ".....kkqqqqqqqqqqqqqqqqqqkk.....",
      ".....kkKKKKKKKKKKKKKKKKKKkk.....",
      "......kqqqqqqqqqqqqqqqqqqk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kKKKKKKKKKKKKKKKKKKk......",
      "......kkkkkkkkkkkkkkkkkkkk......",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................"
    ],
    "hb": true,
    "map": {
      "s": "#1b2133",
      "S": "#2f3a5c",
      "t": "#7e91bd",
      "k": "#0e1018",
      "q": "#141824"
    }
  },
  "chest": {
    "w": 32,
    "h": 32,
    "rows": [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      ".....kkkkkkkkkkkkkkkkkkkkkk.....",
      "....klTTTTTTTTTTTTTTTTTTTTlk....",
      "....klLLLLLLLLLLLLLLLLLLLLlk....",
      "....kNmmmmmmmmmmmmmmmmmmmmNk....",
      "....klLXLLLLLLLLLLLLLLLLLLlk....",
      "....klLLLLLLLLLLLLLLLLLLLLlk....",
      "....kNNNNNNNNNyYYyNNNNNNNNNk....",
      "....klLLLLLLLLYZZYLLLLLLLLlk....",
      "....klLLLLLLLLYkkYLLLLLLLLlk....",
      "....klLLLLLLLLyYYyLLLLLLLLlk....",
      "....kNmmmmmmmmmmmmmmmmmmmmNk....",
      "....klLLLLLLLLLLLLLLLLLLTLlk....",
      "....klLLTLLLLLLLLLLLLLLTLLlk....",
      "....kNmmmmmmmmmmmmmmmmmmmmNk....",
      "....kkkkkkkkkkkkkkkkkkkkkkkk....",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................"
    ],
    "hb": true,
    "map": {
      "k": "#1c0f08"
    }
  }
};
